spring:
  application:
    name: Spring-rest-soap

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: rest/api-docs
  swagger-ui:
    path: rest/swagger-ui
    disable-swagger-default-url: true
    version: 2.0